INSERT INTO board (title,writer,content) VALUES ('오늘 만든거','whddls','내용1');
INSERT INTO board (title,writer,content) VALUES ('물어볼게 있어요','whddls','내용2');
INSERT INTO board (title,writer,content) VALUES ('미나리전을 만들어봤슴','whddls','내용3');
INSERT INTO board (title,writer,content) VALUES ('오늘 저녁','hong','내용4');
INSERT INTO board (title,writer,content) VALUES ('고기 구워왔음','hong','내용5');
INSERT INTO board (title,writer,content) VALUES ('이거 진짜 오랜만에 먹어봐','qwer','내용6');
INSERT INTO board (title,writer,content) VALUES ('라이스카레','kim','내용7');
INSERT INTO board (title,writer,content) VALUES ('풀드포크에 같이 먹을거 추천해줘','park','내용8');
INSERT INTO board (title,writer,content) VALUES ('토리파이탄 & 카라아게','park','내용9');
INSERT INTO board (title,writer,content) VALUES ('오늘 맹근거','lee','내용10');
INSERT INTO board (title,writer,content) VALUES ('오늘 저녁은 볶음밥','lee','내용11');
INSERT INTO board (title,writer,content) VALUES ('저녁반찬으로 쏘야볶','abc','내용12');
INSERT INTO board (title,writer,content) VALUES ('오늘 아침식사','whddls','내용13');
INSERT INTO board (title,writer,content) VALUES ('탕수육 만듬','whddls','내용14');
INSERT INTO board (title,writer,content) VALUES ('롯데리아 신메뉴 후기','whddls','내용15');
INSERT INTO board (title,writer,content) VALUES ('차완무시 해봤음','hong','내용16');
INSERT INTO board (title,writer,content) VALUES ('점심집밥','hong','내용17');
INSERT INTO board (title,writer,content) VALUES ('간단한 저녁','qwer','내용18');
INSERT INTO board (title,writer,content) VALUES ('볶음밥 하다가 기름 튀는데','kim','내용19');
INSERT INTO board (title,writer,content) VALUES ('레몬 버터 파스타','park','내용20');
INSERT INTO board (title,writer,content) VALUES ('파슬리 파는곳이 없어...','park','내용21');
INSERT INTO board (title,writer,content) VALUES ('집에서 만들어본 선지해장국','lee','내용22');
INSERT INTO board (title,writer,content) VALUES ('딸깍도 요리로 봐줌?','lee','내용23');
INSERT INTO board (title,writer,content) VALUES ('직접만든 칠리새우 보고가','abc','내용24');
INSERT INTO board (title,writer,content) VALUES ('오늘은 저녁으로 제육을 했숴','abc','내용25');
INSERT INTO board (title,writer,content) VALUES ('오늘 저녁은 등심스테이크','abc','내용26');
INSERT INTO board (title,writer,content) VALUES ('쿠우쿠우를 갔다오다','abc','내용27');

INSERT INTO comment (board_id,nickname,body) VALUES (1,'익명1','댓글1');
INSERT INTO comment (board_id,nickname,body) VALUES (1,'익명2','댓글2');
INSERT INTO comment (board_id,nickname,body) VALUES (1,'익명3','댓글3');
INSERT INTO comment (board_id,nickname,body) VALUES (2,'익명4','댓글4');
INSERT INTO comment (board_id,nickname,body) VALUES (2,'익명5','댓글5');
INSERT INTO comment (board_id,nickname,body) VALUES (2,'익명6','댓글6');
INSERT INTO comment (board_id,nickname,body) VALUES (2,'익명7','댓글7');