DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS board_image;
DROP TABLE IF EXISTS board;
DROP TABLE IF EXISTS users;

CREATE TABLE board (
	seq BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(200) NOT NULL,
	writer VARCHAR(20) NOT NULL,
	content VARCHAR(2000) NOT NULL,
	regdate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	cnt INT DEFAULT 0 NOT NULL
);

CREATE TABLE comment (
	id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	board_id BIGINT,
	nickname varchar(255),
	body TEXT,
	regdate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updatedate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (board_id) REFERENCES board(seq) ON DELETE CASCADE 
);

CREATE TABLE board_image (
	id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	url VARCHAR(200) NOT NULL,
	board_id BIGINT,
	FOREIGN KEY (board_id) REFERENCES board(seq) ON DELETE CASCADE 
);

CREATE TABLE users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255),
    email VARCHAR(255),
    password VARCHAR(255),
    role VARCHAR(255),
    authority VARCHAR(255)
);